version: '3'
services:
  identifier:
    build: ./identifier
    ports:
      - "5000:5000"
  kraken_designer:
    image: devopsfaith/krakendesigner:latest
    ports:
      - 8787:80
  krakend_ce:
    image: devopsfaith/krakend:1.0.0
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "8080:8080"
    depends_on:
      - identifier

