version: '3'
services:
  postgresdb:
    container_name: postgresdb
    image: "postgres"
    ports:
      - "6432:5432"
    restart: always
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: brian

  api_service:
    container_name: api_service
    build: .
    # restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - postgresdb
    command: ["sh", "start.sh"]
        
