version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - "db:database"
  db:
    image: "postgres"
    ports:
      - "5431:5432"
    restart: always
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: database
