swagger: "2.0"
info:
  description: "This is a sample server for a school project"
  version: "1.0.0"
  title: "Attendance Taking"
basePath: "/api"
tags:
- name: "enrollment"
  description: "Everything about enrollment"
- name: "Identify"
  description: "Everything about identifying ppl"
- name: "Event"
  description: "Everything about events"
schemes:
- "https"
paths:
  /event:
    get:
      tags:
      - "Event"
      summary: "Retrieve all events by name"
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: The name of the event
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: "#/definitions/Event"

  /event/new:
    post:
      tags:
      - "Event"
      summary: "Add a new event"
      responses:
        '200':
          description: 'OK'
      parameters:
      - in: "body"
        name: "body"
        description: "Event object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Event"

  /user/login:
    get:
      tags:
      - "user"
      summary: "Login the user"
      responses:
        '200':
          description: 'OK'

definitions:
  Event:
    type: "object"
    properties:
      name:
        type: string
      createdBy:
        type: string
      dateTimeStart:
        type: string
        format: date-time
      dateTimeEnd:
        type: string
        format: date-time
      locations:
        type: array
        items:
          type: integer


