"""Added createdBy column to Events

Revision ID: 1b23a80af453
Revises: fb55c4c02cf6
Create Date: 2020-01-14 09:55:30.988436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b23a80af453'
down_revision = 'fb55c4c02cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('createdBy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Events', 'createdBy')
    # ### end Alembic commands ###
