"""Added Event Table

Revision ID: fb55c4c02cf6
Revises: 6a643ce5f814
Create Date: 2020-01-12 11:21:11.366170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb55c4c02cf6'
down_revision = '6a643ce5f814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sesPerWeek', sa.Integer(), nullable=True),
    sa.Column('numOfWeek', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_constraint('Features_attendee_id_key', 'Features', type_='unique')
    op.drop_column('Features', 'dateTimeRecorded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Features', sa.Column('dateTimeRecorded', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint('Features_attendee_id_key', 'Features', ['attendee_id'])
    op.drop_table('Events')
    # ### end Alembic commands ###
