"""empty message

Revision ID: 57e995e37377
Revises: 
Create Date: 2020-01-28 15:27:54.829576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e995e37377'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'course', ['name'])
    op.create_foreign_key(None, 'event', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'year', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'year', type_='unique')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='unique')
    # ### end Alembic commands ###
