"""empty message

Revision ID: 8c8038f6b0d1
Revises: 9ef7f009f00f
Create Date: 2020-01-16 16:55:22.925548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8038f6b0d1'
down_revision = '9ef7f009f00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'meme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('meme', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
